name: rufus.abbott
description: access
version: 0.0.1
author: zwmbjobg.p7ricdhe@zftjrisv.com
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines:
  pipelines/Tricia_LynchTad_PohlLorri_Bradtke:
    name: Tricia_LynchTad_PohlLorri_Bradtke
    description: null
    author: zwmbjobg.p7ricdhe@zftjrisv.com
    mode: batch
    artefactID: ''
    language: sql
    createdAt: '2025-12-05 22:45:03'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-12-05 22:45:03'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: zwmbjobg.p7ricdhe@zftjrisv.com
  createdAt: '2025-12-05 22:45:03'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
